# Generated by Django 5.2.5 on 2026-02-06 01:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comentario_perfil_seguidor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seguidor',
            unique_together={('seguidor', 'seguindo')},
        ),
    ]
